### ISSUE TITLE
[Quest] Captain Vimes

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [OregonCore/OregonCore#1290]
**Revision**: e7036ac+

**Operating system**: Windows Webserver 2008 RC2

**Current behavior**: 
....

**Expected behavior**: Captain Vimes should see the orc report you found, <name>. He knows the orcish language better than most. And he should know that there are Horde spies near Theramore!

The captain is in the barracks, on the northeastern side of Theramore Isle. 
...

**Steps to reproduce the problem**:  The quest will not be offered by the quest giver. They can therefore not accept. This is actually a pretty long quest series, the EP and much good objects, and missing completely.

The beginning of the quest series is: http://www.wowhead.com/quest=1219/deprecated-the-orc-report The Sai can be indicative, and then is unfortunately already end as the sequence does not get quest.

**Comment by adeutscher** [comment]
It looks to me like the database thinks that the Captain Vimes quest (Quest number 1220) is started by "Theramore Lieutenant " (Creature Id #4947). Aside from being counter-intuitive since you're turning the previous quest into "Lieutenant Aden" (Creature Id 23951), there is no instance of a "Theramore Lieutenant" in the database at all without GM meddling.

Quick query to see which NPCs the database thinks are handing out quest number 1220 or quests that the database thinks that Lieutenant Aden should be handing out:
`SELECT * FROM creature_questrelation WHERE id=23951 OR quest=1220;`

Query to confirm NPC instances by name:

`SELECT ct.entry, ct.name Name, c.position_x,c.position_y,c.position_z,c.map FROM creature c RIGHT JOIN creature_template ct ON c.id=ct.entry WHERE ct.name="Lieutenant Aden" LIMIT 5;`

Statement to add the quest entry to the database (will be making a properly-formatted update for this shortly):
`INSERT INTO creature_questrelation(`id`,`quest`) VALUES(23951,1220);`

The comments in the Wowhead entry for the quest ([link](http://www.wowhead.com/quest=1220/deprecated-captain-vimes)) suggests that the quest line stops right here for the Alliance. However, Horde players should be able to find a similar note in the same place as Q#1219 that opens up a much bigger line..

Also from Wowhead (comments for the [newer version](http://www.wowhead.com/quest=27247/captain-vimes) of the same quest), Vimes is apparently supposed to do some emoting and scripted text after a player turns in the quest. Since this is a different can of worms from Aden not handing out the quest, I'll make a separate issue for it.
