### ISSUE TITLE
Switching Between Find Herbs and Find  Minerals

### ISSUE THREAD

**Issue by ghost** [OregonCore/OregonCore#1302]
**Revision**:
actual
**Operating system**:
Windows Server 
**Current behavior**: 
Cannot switch from Find herbs to find Minerals
but Posible from Minerals to Herbs
**Expected behavior**: 
Posible to Switch from Herbs to Mierals

**Steps to reproduce the problem**:
Leran it and test it

**Comment by adeutscher** [comment]
Looks to me like the problem is that the original tracking aura is never dispelled when the new one is applied, but the tracking value is overwritten. A tracking won't allow itself to be applied while it is already still active.

Each link of the following chains work. Disabling the tracking on the minimap will change the icon to the previous tracking in the chain, but `Aura::HandleAuraTrackResources` will still have set the sel the tracked resource to "Nothing".

In addition, toggling to tracking utilities properly disables resource tracking.

For example:
- None->Minerals->Treasure->Herbs: Each of these actions works. Herbs->Minerals/Treasure would fail.
- Treasure->Innkeeper->Treasure: Works

Something must be going wrong in `Unit::RemoveNoStackAurasDueToAura` so that the resource-tracking auras aren't seen as conflicting with one another as they should.

Another strange behavior:
- None->Treasure->Humanoids: Both trackings are working at once.
- None->Treasure->Humanoids->Innkeeper: Tracking humanoids is removed, only Track Treasure works.
- None->Treasure->Humanoids->Innkeeper->Repairs: Only repairs work.

To confirm, is it intended for any type of tracking to stack in this expansion?

**Comment by adeutscher** [comment]
My current change for this will wipe all existing tracking auras (both resource and creature) when a new aura is applied. I can switch this to be type-specific in case someone can confirm that the two types should stack.
