### ISSUE TITLE
Zaffy please read this you miss sql updates

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1317]
**Revision**: latetst batch of updates by zaffy

**Operating system**: unix

**Current behavior**: I saw you uploaded to repo alot of fixes in 1 bunch, great and very faithful that alot of progress have been made, but they all miss database update to update the creature_template with the new script if you know what i mean, it might be that you forgot them or didnt think of them.
but most new scripts are not assigned in the database to a creature.
....

**Expected behavior**: scripts are attached to creatures in the creature_template
...

**Steps to reproduce the problem**: let zaffy upload a bunch of fixes and give him more beer then he can handle so he forgot the sql update ^^ ( joke )

**Comment by dikkedeur** [comment]
also creature text are missing in some commits,

**Comment by Zaffy** [comment]
About 2-3 big commits remain but they should be merged with care since the code is quite old. All credits go to @Selphius . I'll try to find those sqls but most probably he didn't provide them nevertheless if I don't hear from him we should assign the scripts ourselves.

**Comment by dikkedeur** [comment]
okay and then also the text, in case you need help maybe i can find some of my own, regardless if it comes to text..

**Comment by Selphius** [comment]
HAHAHA, never thought you will USE all my fixes :P most of them were done by me when I started scripting, so they are "mostly longer" than needed, but they worked perfect for me. Also they were done BEFORE "SAI" function was added so I don't know if some crashes won't occur.

Since you used all my fixes, you should have "almost perfect" Outland and ALL quests working, except some which I didn't either found or didn't have any idea how to get them blizzlike (it will be no more than 10-20 I think). 

I haven't been doing sql's commits since I didn't know how to before, and didn't see it as necessary since I commited it to myself. I have full "DB" which worked for me. Lots of changes mostly with creatures "EventAI" all mobs of Outland had been scripted by it and every mob have their skills. If you want ENTIRE creature_template_table with it from me, feel free to say so. Though there can be problems since it doesn't have SAI.

I will try to made those missing sql for my fixes, so no worries.

Edit: @Zaffy you can change @Raisken to @Selphius since I just switched username, since everyone from Oregon knows me by than name :]

**Comment by dikkedeur** [comment]
wow, okay thanks, looks great, we must then only assign them to the npc's and commit it, im currently working and a busy weekend to go, but i might get to work on it and make a push request.

**Comment by HEGladios** [comment]
Hi @Selphius, nice to see so many fixes.
Is there any progress on the missing SQLs?
I'd love to start using these, but without the SQL files there's no point having these in the repo :D

**Comment by Zaffy** [comment]
Updated by  a76b37d. Not all these errors were resolved but many were.
