### ISSUE TITLE
[Quest] you Robot.

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1337]
**Revision**: latest

**Operating system**: unix

**Current behavior**:  when you accept quest, negatron is spawned, he is neutral/green.. it seems that script doesnt go further, if i look on the script the dokter should yell: Oh no! What's that!? Quickly, defend us with the Scrap Reaver X6000!!!, that doesnt happen, maybe since this code:
if (Creature\* negatron = me->FindNearestCreature(NPC_NEGATRON, 30.0f, true))
its more then 30 ?? and it doesnt get triggered??

....

**Expected behavior**: when you accept quest, the negatron should spawn and walk towards the quest location, then events begins to kill him with the scrap reaver.
...

**Steps to reproduce the problem**: take quest and see for yourself.

**Comment by Selphius** [comment]
No, no it works perfectly fine, and all the code is correct - this script quest was written by me, so it worked when I tested it. It works like that:
1. You accept quest, and negatron spawns 50y+ away.
2. He is moving to direction of you, and quest giver, when he reaches 30y. quest giver yells this line which you mentioned.
3. Negatron talks some lines and turns hostile and you fight him.
4. You kill him, and quest completes.

So basically the problem must lay in point 2, since you have no MovePath for Negatron, I guess.
`me->GetMotionMaster()->MovePath(601601605, false);` 
If I remember was my custom made path, since I don't know the correct one (600600600+ where my custom made) - should be sniffed from retail by someone, so it would be blizzlike.

So I recommend you make your own movepath and switch mine for yours, or check any video of this quest make path and commit :D

**Comment by dikkedeur** [comment]
the path... can you share that one? since that is indeed the problem, he spawns to far away so the whol script stops since he doesnt get in range :P
