### ISSUE TITLE
Quest A Dip in the Moonwell (9433) - bug with robot

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1448]
**Revision**:
last
**Operating system**:
serv2008R2
**Current behavior**: 
On this quest you should take some water from the moonwell by controlled robot - this part is ok
But you can not release robot by clicking on "cancel" - nothing happens
- when time is over, robot starts to attack you

**Expected behavior**: 
Robot should be release by clicking on cancel and disappear
![2](https://cloud.githubusercontent.com/assets/6802530/16313037/0bfa91da-3980-11e6-9f08-a87662239c21.png)

**Steps to reproduce the problem**:

**Comment by zhy9934** [comment]
In the Chess event , it have same situation  when i controlled the piece

**Comment by Desteny** [comment]
on checss i noticed this one as well, it helps to not use the cancel button but there is a buff upon, if you remove the buff by clicking it cancels.

**Comment by PadreWoW** [comment]
Why close?
Bug is still here!

**Comment by Selphius** [comment]
This bug is related to PetAI, not only to this one particular quest. It would be better to create issue about this PetAI and it's behaviour, as well as list of all affected npc's by it. That way we can fix this issue in one go, rather than 1 by 1, that's why I closed this issue :P

Ps. tested it several times on my end, when time is up mob still remains neutral to me - doesn't attack nor I can attack (tried like 10 times). Only the "dismiss/cancel" icon doesn't work like you reported.
