### ISSUE TITLE
Ghosts (dead player) can not walk on water

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1455]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
Ghosts can not walk on water

**Expected behavior**: 
Ghosts should walk on water

**Steps to reproduce the problem**:

**Comment by PadreWoW** [comment]
small correction - Ghosts (dead player) can not walk on water if player dies in dungeon - in my case it was "The Slave Pens" dungeon

**Comment by Desteny** [comment]
@ Slave Pens you need to get under water to get to your corpse, right? for this reason you cant waterwalk.

i remember this was the reason, and i remember that people told this is blizzlike...

**Comment by PadreWoW** [comment]
Where can I fix it?

**Comment by WaCzup** [comment]
And the other dungs bug have this bug too? Or just **Slave Pens**, **The Underbog**, **The Steamvault** and **Serpentshrine Cavern** which they need that because **they are under water**? :]

**Comment by ghost** [comment]
@Desteny That is not blizzlike. Blizzlike behavior would be you walk on water until you look down and move forward (point the camera below the horizon and move forward by using both mouse buttons).

It is the same functionality as death knight's Path of Frost and the shaman water walking spell. It has been like this since the game was first released so it is not an expansion change.

**Comment by Desteny** [comment]
@Saben65  thanks for the info. as far as i know there is a IF in the code with the zoneID where the logic changes for waterwalk in ghost form. i cant remember where it was, but it can be probably changed since years. it could be a hint but cant remember more details, maybe search in the code with the zoneid  maybe you find it
