### ISSUE TITLE
Every user with any level can go trough Dark Portal

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1461]
**Revision**:
last
**Operating system**:
serv2008R2
**Current behavior**: 
Every user with any level can go trough Dark Portal
areatrigger_teleport + access_requirements are not working

**Expected behavior**: 
Dark Portal should be availible only at 58 level

**Steps to reproduce the problem**:

**Comment by PadreWoW** [comment]
Tested on clear core without any third-party patches

**Comment by ghost** [comment]
Blizzard did remove the level restriction from walking through the dark portal at some point; however, I couldn't find any patch notes for when so I am assuming it went undocumented. The closest I could find [was this](http://www.wowhead.com/zone=3483/hellfire-peninsula#comments:id=20298:reply=167318) from 3.3.3 where a user says he was able to walk in before level 58. 

I am assuming the change took place post-TBC and the expected behavior should be how PadreWoW describes.
