### ISSUE TITLE
Do you accept pull requests for custom features?

### ISSUE THREAD

**Issue by Schaka** [OregonCore/OregonCore#1485]
If they are bound to a config option, of course.
I'm thinking along the lines of, say, the AH bot.

Mostly because I know there are a bunch of PvP features that make TBC more playable if having server side support. I'm thinking along the lines of Gladdy/Proximo server side support (for addon keybinds, like in patch 3.x), arena spectator, etc.

I have the rest of the week off and am looking for something to occupy my mind without it going to waste.

@LordUsagi

**Comment by Baynar** [comment]
I have asked for this before and the answer was 
@LordUsagi :"We try to stay away from it as much as possible, unless it makes sense. What did you have in mind?"
so improvements to custom command / already existing stuff is welcome and other thing you might want in a blizzlike 2.4.3 server not in a Fun server or Custom server, Arena spectator, etc are really custom and i am certain they won't be accepted

But you can make your Custom Repo and ask @Zaffy and @LordUsagi  if they wanna add a non supported by them custom branch

**Comment by Zaffy** [comment]
I have realized the need for custom stuff quite long ago. I wanted to make OC modular (so it would have its own plugin system). I worked on the system first months (not 24/7 ofc) this year but didn't really have enough time and energy to finish it, since I was up to fixing bugs as well as running my personal life. And I did not resume the work again. And now it's summer and my family quite "spends my time", and also there's more importatnt issues in my mind to fix - stability issues caused by the popular unpleasant grid system update. A very tough crash i didn't solve yet. But if anyone of you is interested in helping with the plugin/modular system I can share with you what I have done and you can help to design and implement it in a better way, or at least make a working prototype.

**Comment by LordUsagi** [comment]
Yes we absolutely support well founded pull requests for custom features.
