### ISSUE TITLE
Is oregoncore being developed still?

### ISSUE THREAD

**Issue by DanielBallaSZTE** [OregonCore/OregonCore#1499]
So I realised there hasn't been a single commit nor help on forums for more than a month. I really would like to fix bugs but can't since there is literally 0 help on understanding how scripting / core coding works, how to do basic stuff.
So the question is, are the devs out, did they give up on the core? Is it a dead project?
Didn't want to post it on oregoncore forums since no one checks that, there is a bigger chance here devs are going to see this and probably give some information on the future of the project.

**Comment by DkVagabonden** [comment]
Well, i think it will start soon again, everyone been on holliday and needs to get back into the mood to do all this.

**Comment by Desteny** [comment]
the development seems to be stopped an noone knows if it will continue or not, the major problem is that the main devs lordusagi and zaffy don't have time and i think they will retire (but its only my subjective impression)

there where some new devs around but i haven't heared much since months and they have done some commits but no major work.

on forums i answer on detailed questions and i give feedback on nearly 60% of all topics.
but i will not write any how to dos and will not explain basic stuff for the last almost 8 years ever and ever again. 

for get started use the wiki, or the old wiki (linked on OC homepage) or search on forums.
but to start working realy with OC you need to read the code, thats all, all questions are explained in code and if there are detailed questions with related research (code lines) someone will respond your question (or maybe noone cause nobody knows)

**Comment by DanielBallaSZTE** [comment]
https://forums.oregon-core.net/viewtopic.php?id=569

Yeah like this one. 
I mean, I know the fix for those bugs, I just don't know how to implement it in OregonCore. But I'll try and search for comments that help me understanding how to add a damage modifier to a spell etc. 

Anyways, thanks for the info.
