### ISSUE TITLE
Oregon is DEAD?

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1508]
## **Operating system**:

**Current behavior**: 
http://oregoncore.lunar.sk/ - Not Found
The requested URL / was not found on this server.
+
no new commits, no DEVs are here
what's happening????
Where are you all???

**Expected behavior**: 
...

**Steps to reproduce the problem**:

**Comment by ghost** [comment]
I believe is actually dead... but not sure...

**Comment by kotishe** [comment]
Best core evar, no have time now for fix dungeons in my fork =(
And no devs here((((

**Comment by ghost** [comment]
open source project cannot die, it's just in idle mode and if you want to make it more alive feel free to fix and push

**Comment by PadreWoW** [comment]
where are Zaffy and LordUsagi ???

**Comment by Desteny** [comment]
> open source project cannot die, it's just in idle mode and if you want to make it more alive feel free to fix and push

+1 for this, its exactly what i try to tell since years.
everyone is welcome to contribute :)

**Comment by miraco** [comment]
Maybe they have some real life too?

**Comment by zgn1988** [comment]
Hi, https://bitbucket.org/zgn/projecttbc/commits/all
if you want to help, join

**Comment by Zaffy** [comment]
@PadreWoW  oregoncore.lunar.sk redirected always to forums.oregon-core.net. I used my domain since we didnt have our domain.

@zamalaev Please don't fragment the project. I'd love to see all improvements in official repo, if you're interested I can give you rights so you dou don't have to fragment.

The real thing is that LordUsagi has decided to leftt and I have really hard time leaving OC - I know you don't see me very often here online but believe me that my mind is very busy thinking about OC, nevertheless I dont feel any motivation to be working on OregonCore alone. So if new people come, we can raise it together, again.

**Comment by zgn1988** [comment]
Zaffy, well I'm with you! Add the repository

**Comment by Zaffy** [comment]
Very well then, I sent you invitation here on github. Could you see me on irc?

**Comment by zgn1988** [comment]
okey) link irc channel

**Comment by Zaffy** [comment]
heh I thought you already know about it - irc.foonetic.net and # OregonCore . You can also find a webclient here http://oregon-core.net/

**Comment by zgn1988** [comment]
my name is forum zamalaev

**Comment by kotishe** [comment]
Hello from Tula, nice to meet you!

**Comment by zgn1988** [comment]
Вау)) Я из Калуги))

**Comment by PadreWoW** [comment]
Москва :)

**Comment by zgn1988** [comment]
можно будет на нейтральной территории встретиться отдохнуть)
PadreWoW,kotishe могу ли я Вас добавить в скайп?

**Comment by kotishe** [comment]
Валяй, kotishemsk

**Comment by zamalaev** [comment]
Bye OregonCore
