### ISSUE TITLE
Rename bug

### ISSUE THREAD

**Issue by smoldar** [OregonCore/OregonCore#1577]
If you use rename function. Char will get new name, but core dont know that new name until restart of core.
Example of problems:
1) player cant leave arena team (because have different name - must use /leave 2v2 or /teamquit 2v2, normally cant)
2) nobody cant write to him, other players see old name, but player have new.. they must write /w Newname which they dont see

I think ideal will be when player log ingame will be his name loaded correctly

**Comment by Desteny** [comment]
as far a s i know this issue exists already since TC1 days, but it should be easy to solve.
there are some objects around on the server caching the name.

you simply need to find those and change the name there as well if the renaming will be done or unload the objects should be reloaded after login like on a new started server

**Comment by AbraKabastard** [comment]
Merged into  #1040
