### ISSUE TITLE
OregonCore revived?

### ISSUE THREAD

**Issue by DanielBallaSZTE** [OregonCore/OregonCore#1587]
So it's been a long time since Oregon had some meaningful patches in the past year.

This afternoon though, there have been numerous commits.
Is OregonCore -after such a long time- being maintained again?
I've also seen LordUsagi pushing an update.

If so, what are future plans with the core?
I would be more than happy to help developing Oregon, however I wouldn't like to put time into it, if no further development is planned.

**Comment by AbraKabastard** [comment]
Hello @DanielBallaSZTE ,

OregonCore has had a small nap. I would definitely love to continue contributing to it with like-minded hobbyists. If that's you too, then great!

I do not have any future plans other then to continue maintaining it. I personally would like to bring it as close to Trinitys' 3.3.5 branch as possible due to a number of tangible benefits. This process though, is a very long and difficult one.

Do you have any ideas for the future of Oregon?

Regards,
AbraKabastard

**Comment by DanielBallaSZTE** [comment]
@AbraKabastard Sounds great, I will definitely try and help here and there, although I'm not really familiar with the core itself.

Do you know anything about @LordUsagi or @Zaffy ? They are the 2 main developers I've known.

**Comment by AbraKabastard** [comment]
@DanielBallaSZTE 

I have no clue on their whereabouts. I've been given high permissions on GitHub that I can manage the project during their absence.

**Comment by Desteny** [comment]
Nice to see your recent commits here @AbraKabastard , i like the idea to bring oregon closer to TC 3.3.5.

Back in time ~2010 i was following this idea as well, and ported a lot over. 
But this is a lot of work and a never ending story cause TC develops rapidy and shure OC is far behind now... 

About Zaffy and LordUsagi i can't tell you more details, but ages ago they had a lot to do in their RL and like everyone of us, priorities are changing and "maybe" they are not running servers any more and in the most case this ends up with no more work on this project (but like i sayed, i don't know this for sure)

good luck and have fun with OC

**Comment by kotishe** [comment]
Hi all. Nice start again! Yeah!
