### ISSUE TITLE
Omen (BB #736)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#736]
This issue was migrated from bitbucket.
**Original Reporter:** Areradon
**Original Date:** 06.11.2014 09:31:37 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** new
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/736

<hr>

The Addon Omen should show the thread from a Player on a mob.

It feels that it shows wrong data. For example at Void Reaver after first aggro reset from the Tank it show wrong. Or if you taunt it show you, you are up again but he should be taunt imun.

The Core give the AddOn wrong data. (Omen and DBM support for the Core)

**Comment by Selphius** [comment]
Prove me wrong, but from my knowledge Omen never shows reset threat / aggro drop. It's coded this way by modder who created it, especially at versions for Vanilla/TBC where addons weren't that good of quality to begin with. So it's not OregonCore's problem for it's behaviour, it's inside Omen's script for earlier versions which support 2.4.3. So rather than come here with this issue, you should go to the creator of the addon. If you have any evidence regarding I am wrong, please give me any kind of proof to support your claim.

As for DBM it's working like it should, it's faulty behaviour can be seen, by bad timers in scripts of some bosses. (They need to be corrected / spells added etc. so DBM can find what it looks for and function properly).
